import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut } from "next-auth/react";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Cognito</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="mb-4 text-2xl font-bold text-white">Cognito</h1>
        {session ? (
          <>
            <p className="mb-6 text-lg text-white">
              Signed in as {session.user?.email}
            </p>
            <button
              onClick={() =>
                void signOut({
                  callbackUrl: "signOut",
                })
              }
              className="mr-2 mb-2 rounded-lg bg-gradient-to-r from-red-400 via-red-500 to-red-600 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-red-300 dark:focus:ring-red-800"
            >
              Sign out
            </button>
          </>
        ) : (
          <button
            className="mb- mr-2 rounded-lg bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-800"
            onClick={() => void signIn("cognito")}
          >
            Sign in
          </button>
        )}
      </main>
    </>
  );
};

export default Home;
